
% Version History
% 092105        SSP         Initial write

function [] = HeaderParam(obj, parname, parval, x, y, varargin)

   if ischar(obj) && strcmp(obj, 'base'), param_owner = 'base';
   elseif isobject(obj),                  param_owner = ['@' class(obj)];
   else   error('obj must be an object or the string ''base''');
   end;

   pairs = {   ...
     'param_owner',        param_owner            ; ...
     'param_funcowner',    determine_fullfuncname     ; ...
     'position',           gui_position(x, y)         ; ...
     'width',              400                        ; ...
     'height',             15                         ; ...
   }; parseargs(varargin, pairs);

   position(3) = width;
   % position(4) = height;

   SoloParamHandle(obj, parname, ...   
                   'type',            'header', ...
                   'value',           parval, ...
                   'position',        position, ...
                   'param_owner',     param_owner, ...
                   'param_funcowner', param_funcowner);

   assignin('caller', parname, eval(parname));
   return;

