function [ed] = NumeditParam(obj, parname, parval, x, y, varargin)
%
% Creates a numedit SoloParamHandle of name given by parname, value by
% parval, and with the lower left-hand corner of the numedit's GUI at
% x, y.
%
% Numedit is like Edit, except it can only take scalar numbers.
%   
   
   
% Version history
% 092905:   Carlos      Initial write

   if ischar(obj) && strcmp(obj, 'base'), param_owner = 'base';
   elseif isobject(obj),                  param_owner = ['@' class(obj)];
   else   error('obj must be an object or the string ''base''');
   end;


   pairs = { ...
       'param_owner',        param_owner            ; ...
       'param_funcowner',    determine_fullfuncname     ; ...
       'position',           gui_position(x, y)         ; ...
       'TooltipString',      ''                         ; ...
       'label',              parname                    ; ...
       'labelfraction',      0.5                        ; ...
       'labelpos',           'right'                    ...  
       }; parseargs(varargin, pairs);
    
   ed = SoloParamHandle(obj, parname, ...
                        'type',            'numedit', ...
                        'value',           parval, ...
                        'position',        position, ...
                        'TooltipString',   TooltipString, ...
                        'label',           label, ...
                        'labelfraction',   labelfraction, ...
                        'labelpos',        labelpos, ...
                        'param_owner',     param_owner, ...
                        'param_funcowner', param_funcowner);
   assignin('caller', parname, eval(parname));
   return;
   
   
