
% Version history
% 091905        Carlos      Initial write
% 092105        SSP         Added 'label' to pairs
%   - Returns sph object
% 092505        SSP         Older version replaced by Carlos' version from
% 092305; changes from 092105 reproduced



function [pb] = PushbuttonParam(obj, parname, x, y, varargin)

   if ischar(obj) && strcmp(obj, 'base'), param_owner = 'base';
   elseif isobject(obj),                  param_owner = ['@' class(obj)];
   else   error('obj must be an object or the string ''base''');
   end;

   pairs = { ...
       'param_owner',        param_owner            ; ...
       'param_funcowner',    determine_fullfuncname     ; ...
       'position',           gui_position(x, y)         ; ...
       'TooltipString',      ''                         ; ...
       'label',              parname                    ; ...
       'FontWeight'          'bold'                     ; ...
       'BackgroundColor'     [0.75 1 0.75]              ; ...
       'labelpos',           'right'                    ...  
   }; parseargs(varargin, pairs);
    

   pb = SoloParamHandle(obj, parname,        ...
                        'type',            'pushbutton', ...
                        'position',        position, ...
                        'TooltipString',   TooltipString, ...
                        'label',           label, ...
                        'labelpos',        labelpos, ...
                        'FontWeight',      FontWeight, ...
                        'BackgroundColor', BackgroundColor, ...
                        'param_owner',     param_owner, ...
                        'param_funcowner', param_funcowner);
   assignin('caller', parname, eval(parname));
   return;
   
