
% Version history
% 092105        SSP         Initial write

function [] = SubheaderParam(obj, parname, parval, x, y, varargin)

   if ischar(obj) && strcmp(obj, 'base'), param_owner = 'base';
   elseif isobject(obj),                  param_owner = ['@' class(obj)];
   else   error('obj must be an object or the string ''base''');
   end;
   
   pairs = {   ...
     'param_owner',        param_owner            ; ...
     'param_funcowner',    determine_fullfuncname     ; ...
     'position',           gui_position(x,y)          ; ...
     'width',              []                         ; ...
     'height',             []                         ; ...
   }; parse_knownargs(varargin, pairs);

   if ~isempty(width),  position(3) = width;  end;
   if ~isempty(height), position(4) = height; end;
   
   SoloParamHandle(obj, parname,  ...
                   'type',            'subheader', ...
                   'value',           parval, ...
                   'position',        position, ...    
                   'param_owner',     param_owner, ...
                   'param_funcowner', determine_fullfuncname);
   
   assignin('caller', parname, eval(parname));
   return;
   
