
% Version history
% 091905:   Carlos      Initial write
% 092105:   SSP         
%   - Added 'TooltipString', 'label' (in 'pairs'), labelpos
%   - EditParam returns itself as an object
% 092405:   SSP         Replaced old file with Carlos' versions and re-made
% changes made on 092105


function [ed] = TextBoxParam(obj, parname, parval, x, y, varargin)

   % BACKWARDS COMPATIBILITY HACK
   % There is an old Exper EditParam.m function (in the Utility
   % directory). If we are called with only two parameters, it must be
   % someone trying to call the old EditParam.m. That function has been
   % copied to Utility/ExperEditParam.m ; let's call it.
   if nargin<4,
      global exper;
      
      if     nargin == 2, ExperEditParam(parname, parval);
      elseif nargin == 1, ExperEditParam(parname);
      elseif nargin == 0, ExperEditParam;
      end;
      return;
   end;
   % --- End BACKWARDS COMPATIBILITY HACK

   if ischar(obj) && strcmp(obj, 'base'), param_owner = 'base';
   elseif isobject(obj),                  param_owner = ['@' class(obj)];
   else   error('obj must be an object or the string ''base''');
   end;
   
   pairs = { ...
       'param_owner',        param_owner            ; ...
       'param_funcowner',    determine_fullfuncname     ; ...
       'position',           []                         ; ...
       'TooltipString',      ''                         ; ...
       'label',              parname                    ; ...
       'labelfraction',      0.5                        ; ...
       'labelpos',           'right'                    ; ...  
       'HorizontalAlignment' 'right'                    ; ...
       'nlines'              5                          ; ...
       }; parseargs(varargin, pairs);

   if isempty(position),
      position = gui_position(x, y);
      position(4) = position(4)*nlines;
   end;
   
   ed = SoloParamHandle(obj, parname, ...
                        'type',            'textbox', ...
                        'value',           parval, ...
                        'position',        position, ...
                        'TooltipString',   TooltipString, ...
                        'label',           label, ...
                        'labelfraction',   labelfraction, ...
                        'labelpos',        labelpos, ...
                        'HorizontalAlignment', HorizontalAlignment, ...
                        'nlines',          nlines, ...
                        'param_owner',     param_owner, ...
                        'param_funcowner', param_funcowner);
   assignin('caller', parname, eval(parname));
   return;
   
   
