
% Colors that the various states take when plotting
SC = struct( ...
  'wait_for_cpoke',  'w',              ...  
  'wait_for_apoke',  [0.7 0.7 0.95],   ...  
  'left_reward',     [0.5 0.9 0.5],    ...
  'right_reward',    [0.5 0.9 0.5],    ...
  'drink_time',      [0.5 0.9 0.5],    ...
  'left_dirdel',     [0.5 0.9 0.5],    ...  
  'right_dirdel',    [0.5 0.9 0.5],    ...
  'pre_odor',       [0.7 0.7 0.7],    ...
  'odor',           [0.28 0.28 0.7],  ...
  'timeout',         [0.6 0.12 0.12],  ...
  'iti',             [0.7 0.7 0.7],    ...
  'dead_time',       [1 0.75 0.75],    ...
  'state35',         [0.3 0.3 0.3],    ...
  'extra_iti',       [0.9 0 0]);


% Which states to plot, together with which event indices indicate an
% exit from that type of state
plottables = { ...
  'dead_time'          1:7   ; ...  
  'wait_for_cpoke'     1:6   ; ...
  'pre_odor'          1:7   ; ...
  'odor'              1:7   ; ...
  'wait_for_apoke'     1:6   ; ...
  'left_reward'        1:7   ; ...
  'right_reward'       1:7   ; ...
  'drink_time'         1:7   ; ...
  'timeout'            1:7   ; ...
  'extra_iti'          1:7   ; ...
  'iti'                1:7   ; ...
             };

